### ISSUE TITLE
running IsobarQuant preMascot step

### ISSUE THREAD

**Issue by saifsikdar** [protcode/isob#10]
Hi @tobymathieson @holfra @gavswe 

I am trying to follow your TPP-TR analysis pipeline mentioned in Franken et al (2015) Nature Protocol. Although I have some experience with R language but I am totally new to python. I recently got TPP-TR experiment's **.raw** files from a Lumos mass-spec. I got these .raw files (vehicle vs. treatment) from our core mass-spec facility. I do not have Xcalibur software installed in my PC. 
1. Can you please let me know if it is still possible to run the preMascot workflow mentioned in your supplementary manual for IsobarQuant package?
2. Is it possible to run your workflow with python 3.8?

I look forward to hearing from you.

Thanks,

Saif

**Comment by tobymathieson** [comment]
Hi Saif, 
Thanks for your interest in isobarQuant! In order for the python code to be able to access the data in the raw file, isobarQuant has to use the interface provided by Thermo, which is Xcalibur. In order for isobarQuant to be able to talk Xcalibur we had to compile an interface to it. This is currently only available for python2.x
So to answer your questions:
1. No, you cannot run the preMascot workflow without having Xcalibur installed on your work station. I believe this is freely downloadable (you may have to register your address somewhere; or talk to your core facility, they might be able to send you a copy of the software - as far as I recall it's not licensed by user number)
2. No it is only possible to run the workflow using python2.x. The python msi for windows should be downloadable still, even though python2 is no longer officially supported. The required .whl files should be available in this repository. 

And linked to the above two points, it is currently also only possible to run the preMascot workflow on a windows environment The postMascot part is entirely possible in the Linux world. 

I hope that answers your questions, sorry if I can't be more helpful ! 

best
Toby

**Comment by saifsikdar** [comment]
Hi @tobymathieson 

Thank you very much for your reply. But it's unfortunate that I do not have Xcalibur software. Is there any free version of this software like freely available codes? I hope that I can get access to Linux OS for post-mascot analysis. Can you please suggest if there is an alternative way to analyze these data to get around the pre-mascot steps? I want to see the melting curve of the target proteins for vehicle vs treatment groups.

Thanks,

Saif

**Comment by tobymathieson** [comment]
Hi again Saif, 

I think that you only need the foundation software - that used to be available for free download (you may have to register) or as I said before just ask your core mass spec facility for a copy of the foundation Xcalibur. 

If you cannot do that and you only want to look at melting curves then you can use the maxquant software to perform the first and second parts of the pipeline (instead of isobarQuant). Its outputs are compatible with the R-scripts in bioconductor: however you will not benefit from the S2I correction of isobarQuant and will have to still download and install maxquant (which I found to be less than straightforward) 

Sorry I cannot be of more help. I have never come across the issue of not being able to get the Thermo Scientific software. 

best
Toby

**Comment by saifsikdar** [comment]
Hi @tobymathieson,

Thank you for your suggestion. 

I was able to manage a copy of Xcalibur 2.2 w/ Foundation 2.0 and installed it on my PC. Then I followed your IsobarQuant software manual and run your code with python 2.7 from the command prompt. This code started running your software but it stopped with an error message suggesting that the Xcalibur is not set up properly. When I opened Xcalibur it showed a popup message that the acquisition service is not running although I could open my .raw files using its Qual browser. I am not sure how to resolve this. 

Can you please provide your suggestion on how to resolve this issue?

Thanks,

Saif

**Code I run:**
(py2) D:\U of C\Lab works\TPP\isob-1.0.0>python preMascot.py --datadir "D:\U of C\Lab works\TPP\exp_data" --quant TMT10
preMascot     : PROCESS  started preMascot application

**Process running message in the command prompt:**
preMascot     : PROCESS  starting 1/2: processing S11174_TMT_10plex_DMSO_201202.raw
pyMSsafe      : WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe/pyMSsafe.py", line 124, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
preMascot     : WARNING  pyMSsafe failed for S11174_TMT_10plex_DMSO_201202.raw: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe/pyMSsafe.py", line 124, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
preMascot     : WARNING  cmd: python "D:\U of C\Lab works\TPP\isob-1.0.0\pyMSsafe/pyMSsafe.py" --datadir "D:/U of C/Lab works/TPP/exp_data" --filefilter S11174_TMT_10plex_DMSO_201202.raw* --pid 8660 --quant TMT10 --general.tolppm 8 --general.tolmda 8 --xic.beforepeak 0.5 --xic.afterpeak 0.5 --logging.logdir logs --logging.loglevel DEBUG --logging.screenlevel WARNING

preMascot     : PROCESS  starting 2/2: processing S11175_TMT_10plex_Staurosporine_201202.raw
pyMSsafe      : WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe/pyMSsafe.py", line 124, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
preMascot     : WARNING  pyMSsafe failed for S11175_TMT_10plex_Staurosporine_201202.raw: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe/pyMSsafe.py", line 124, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
preMascot     : WARNING  cmd: python "D:\U of C\Lab works\TPP\isob-1.0.0\pyMSsafe/pyMSsafe.py" --datadir "D:/U of C/Lab works/TPP/exp_data" --filefilter S11175_TMT_10plex_Staurosporine_201202.raw* --pid 8660 --quant TMT10 --general.tolppm 8 --general.tolmda 8 --xic.beforepeak 0.5 --xic.afterpeak 0.5 --logging.logdir logs --logging.loglevel DEBUG --logging.screenlevel WARNING

preMascot     : WARNING  Errors detected in processing.


**message in the error file**
{'code': 1, 'traceback': 'Traceback (most recent call last):\n  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe/pyMSsafe.py", line 48, in <module>\n    from xRawFile import XRawFile\n  File "D:\\U of C\\Lab works\\TPP\\isob-1.0.0\\pyMSsafe\\xRawFile.py", line 25, in <module>\n    import czXcalibur as czX', 'repr': 'Error: ImportError, Message: DLL load failed: %1 is not a valid Win32 application., Context:  Xcalibur not set up properly', 'context': ['Xcalibur not set up properly'], 'error': 'DLL load failed: %1 is not a valid Win32 application.', 'type': 'ImportError'}

**log files found after running** 
[preMascot.log](https://github.com/protcode/isob/files/5743606/preMascot.log)
[pyMSsafe.log](https://github.com/protcode/isob/files/5743607/pyMSsafe.log)

**message pop up after starting Xcalibur home page and error message screen shot**
![xcalibur acquisition server not running](https://user-images.githubusercontent.com/34520963/103158905-442b3380-4780-11eb-8658-51aa407dc03a.JPG)
![xcalibur home page](https://user-images.githubusercontent.com/34520963/103158908-4b524180-4780-11eb-9d5d-f90dc135ce22.JPG)

**Comment by saifsikdar** [comment]
Hi @tobymathieson ,

Happy new year :)  
I hope you are doing great. Any suggestion on how to solve the issue I am facing?

Thanks,

Saif

**Comment by gavswe** [comment]
Happy New Year Saif,

IsobarQuant doesn’t use the acquisition software so the error in Xcalibur is not a problem.  The problem here is that IsobarQuant is not able to locate the XRawFile2.dll.


  1.  Does the file \Program Files (x86)\Thermo\Foundation\XRawfile2.dll exist on your system?
  2.  Is \Program Files (x86)\Thermo\Foundation in your PATH variable?
  3.  If you have installed Xcalibur in a different location, check that the path to the Foundation folder is part of your PATH variable.

This is not an issue that we have faced before.  Hopefully, one of these suggestions will make a difference to you.

Cheers
Gavain

**Comment by saifsikdar** [comment]
Hi @tobymathieson ,

I checked the XRawfile2.dll file and path. But I am still seeing the same error. Can you please suggest any other option to solve this?
![path](https://user-images.githubusercontent.com/34520963/104082390-0b18a780-51f3-11eb-866d-e2686ff2f780.JPG)

![path2](https://user-images.githubusercontent.com/34520963/104082395-153aa600-51f3-11eb-84e2-32f3f788dd4d.JPG)



Thanks,

Saif

**Comment by tobymathieson** [comment]
Hi Saif, 
And a happy new year from me too. That's very puzzling why it doesn't seem to work for you. Can you try the follow for me? 
Go to the pyMSSafe directory in your installation of ibq and open a 2.7 python shell. The following works for me and might yield where the problem lies (no promises!)
best
Toby

(venv) C:\Users\tm224714\isob\\**pyMSsafe**>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['PATH']
>>> import xcalparser
>>> import xRawFile

**Comment by saifsikdar** [comment]
Hi @tobymathieson ,

2.7 pyhon shell is not opening from pyMSSafe directory. I do not know why it a cmd prompt pops up only for a second. But I could open a python shell from my python 2.7 installed directory. I run these and got the output you see in the attached screenshot. Do you think there was something wrong during installation or unzipping isb?

`import os`
`os.environ['PATH']`
`import xcalparser`
`import xRawFile`

![Capture](https://user-images.githubusercontent.com/34520963/104117201-b05b7a80-52dc-11eb-8bab-e92c8baef45c.JPG)

**Comment by saifsikdar** [comment]
Hi @tobymathieson ,

It looks like DLL loading failing. I am running this from a windows7 environment. Any suggestion on this?

Thanks,

Saif
![Capture](https://user-images.githubusercontent.com/34520963/104231567-6376c180-540c-11eb-92c2-58513e68efae.JPG)

**Comment by tobymathieson** [comment]
Hi Saif,

I am really sorry, but I cannot reproduce your problem . are you starting
your python shell using the python command? Not via a double click?

Toby

**Comment by saifsikdar** [comment]
Hi @tobymathieson ,

I tried both ways but I always get the same problem. Anyway, our collaborator has a software called Peaks, which does some sort of normalization. We got some target hits for staurosporine similar to the paper (Savitski et al 2014 Science) when analyzing data using Peaks. This is why I am thinking of using Peaks for now. Thank you for trying to help me run isobarquant. 

Cheers,

Saif

**Comment by tobymathieson** [comment]
Hi Saif,

Thanks for letting me know - I am very sorry we couldn't get it working for
you  - I am still mystified as to what the problem was !  I have never used
PEAKs for TMT quantification. I hope it performs as well as you need it to.
Be aware that TMT quantification in MS2 spectra is prone to the so-called
ratio compression. As far as I know the only software capable of mitigating
that problem is isobarQuant via its S2I correction alrogithm. An
alternative to MS2-based TMT quantification is to do one further
fragmentation on a peak in the MS2 spectrum (the so-called SPS workflow).
This has been shown to improve quantification accuracy but at the cost of
fewer quantified proteins.

Good luck and best wishes,

Toby
