### ISSUE TITLE
running IsobarQuant preMascot step

### ISSUE THREAD

**Issue by laurenfields** [protcode/isob#12]
Hello,

We are having an issue getting the preMascot.py portion of isobarQuant to run. I noticed [this post](https://github.com/protcode/isob/issues/10) and tried the suggested solutions, but it still isn't working. A couple of notes:

- We are running in python 2
- We have XCalibur installed
- We have confirmed the \Program Files (x86)\Thermo\Foundation\XRawfile2.dll exists and is in the correct location
- The Thermo\Foundation is a path variable

Here is the output error:

```
(py2) C:\Users\mksiv\Documents\isob-master>python preMascot.py --datadir C:\Users\mksiv\Documents\isob-master\Control_1 --quant TMT10
preMascot     : PROCESS  started preMascot application

preMascot     : PROCESS  starting 1/4: processing 2022_0106_C1Multi.raw

preMascot     : PROCESS  starting 2/4: processing 2022_0106_C1T1.raw

preMascot     : PROCESS  starting 3/4: processing 2022_0106_C1T2.raw

preMascot     : PROCESS  starting 4/4: processing 2022_0106_C1T3.raw
pyMSsafe:2022_0106_C1Multi: WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "pyMSsafe.py", line 127, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
pyMSsafe:2022_0106_C1T1: WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "pyMSsafe.py", line 127, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
pyMSsafe:2022_0106_C1T2: WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "pyMSsafe.py", line 127, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]
pyMSsafe:2022_0106_C1T3: WARNING  error: pyMSsafe General error: ['Traceback (most recent call last):\n', '  File "pyMSsafe.py", line 127, in run\n    xraw = XRawFile(str(rawpath))\n', "NameError: global name 'XRawFile' is not defined\n"]

preMascot     : PROCESS  mgf creation of 1/4: processing 2022_0106_C1Multi.raw

preMascot     : PROCESS  mgf creation of 2/4: processing 2022_0106_C1T1.raw

preMascot     : PROCESS  mgf creation of 3/4: processing 2022_0106_C1T2.raw

preMascot     : PROCESS  mgf creation of 4/4: processing 2022_0106_C1T3.raw
preMascot     : PROCESS  Finished processing 4 files
```

We would be very grateful if you could lend any advice in troubleshooting this.
Thanks,
Lauren

**Comment by tobymathieson** [comment]
Hi there, were you able to fix this? At first glance it looks like the pythonpath might not be correctly set?
